apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: hello-world
  name: hello-world-controller
  namespace: default
spec:
  replicas: 2
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: hub-tmp.byu.edu/jgubler/hello-world:latest
        imagePullPolicy: Never
        name: hello-world
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: hub-tmp-byu-edu-dockercfg
      restartPolicy: Always
