#!/bin/bash -ex

mkdir -p ~/.docker
set +x
echo -e $DOCKERCFG | base64 -d > ~/.docker/config.json
set -x
docker build -t $DOCKER_IMAGE:$CI_COMMIT_ID .
docker build -t $DOCKER_IMAGE:latest .
docker push $DOCKER_IMAGE:$CI_COMMIT_ID
docker push $DOCKER_IMAGE:latest
