#!/usr/local/bin/python
import sys
import os
import requests
import json

def send_post(msg):
    response = requests.post(os.environ["SLACK_INCOMING_WEBHOOK_URL"], headers={"Content-Type": "application/json"}, data=json.dumps({"text": msg}))
    print response.text
    response.raise_for_status()

if __name__ == "__main__":
    send_post(sys.argv[1])
